//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 01:12:43 AM EEST 
//


package com.example.subscriber.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.subscriber.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.subscriber.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AllSubscribersRequest }
     * 
     */
    public AllSubscribersRequest createAllSubscribersRequest() {
        return new AllSubscribersRequest();
    }

    /**
     * Create an instance of {@link SubscriberRequest }
     * 
     */
    public SubscriberRequest createSubscriberRequest() {
        return new SubscriberRequest();
    }

    /**
     * Create an instance of {@link SubscriberResponse }
     * 
     */
    public SubscriberResponse createSubscriberResponse() {
        return new SubscriberResponse();
    }

    /**
     * Create an instance of {@link Subscriber }
     * 
     */
    public Subscriber createSubscriber() {
        return new Subscriber();
    }

    /**
     * Create an instance of {@link AllSubscribersResponse }
     * 
     */
    public AllSubscribersResponse createAllSubscribersResponse() {
        return new AllSubscribersResponse();
    }

}
