//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.10 at 05:52:36 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "wsdl-objects", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package wsdl_objects;
